### ISSUE TITLE
`on_return` not called when controller is popped by tapping the tab bar item.

### ISSUE THREAD

**Issue by silasjmatson** [infinitered/ProMotion#603]
See this SO answer: http://stackoverflow.com/a/11912897

When the tab bar item is tapped, it pops the current view controller off of that tab's navigation controller.

However, ProMotion does not hook into this to call `on_return`.

**Comment by jamonholmgren** [comment]
When it's tapped *and it's already the selected tab* *and it's not on the root view controller*, then it'll pop back one. We should be triggering `on_return` in that case.

Of course, `on_return` is more useful when you are programmatically closing, since you can pass in arguments. As a workaround, if you don't want to pass back args, you could just implement `will_appear` and do your refresh or whatever there.
