### ISSUE TITLE
KLCPopup TableScreen

### ISSUE THREAD

**Issue by ronyv89** [infinitered/ProMotion#738]
I am trying to use [KLCPopup](https://github.com/jmascia/KLCPopup) in iOS application. I tried to use a TableScreen as the content view. But the cell contents for the table doesn't seem to load. Any suggestions?

**Comment by markrickert** [comment]
Hey @ronyv89, I've used KLCPopup in a PM::Screen before, but not in a PM::TableScreen. It might be having problems because the `view` of a PM:TableScreen is a UITableView and not a UIView.

Try it on a PM screen and see if it's working. If so, you might need to make your screen a PM::Screen and then create a separate PM::TableScreen and add it to your PM::Screen as a subview.
