### ISSUE TITLE
Error can't convert CommentScreen into String (TypeError)

### ISSUE THREAD

**Issue by naiyyar** [infinitered/ProMotion#800]
Hi,

Getting `can't convert CommentScreen into String (TypeError)` when trying to open an screen from PM::TableScreen's CustomeCell
```
class BlogScreen < PM::TableScreen
  def table_data
		@data = [{
			cells:
			@blogs.map do |blog|
				{
					cell_class: CustomBlogCell,
					height: 200,
	                                properties: {
                                            parent_view: UIView,
	        	                    blog: blog,
          	                            bottom_view: ''"
	                               },
				}
			end
		}]
	end
end
```

```
class CustomBlogCell < PM::TableViewCell
    attr_reader :bottom_view, :parent_view
    def bottom_view=(val)
            @footer_view ||= @parent_view.append!(UIView, :footer_view) do |v|
              @reply = v.append(UIButton, :reply).on(:tap) do |_|
                  open CommentScreen.new(blog: blog, nav: true)
              end
        end
end
```
on reply button tap i'm getting this error.
Is there any way to open a screen like this?

Thanks for the help!

**Comment by jamonholmgren** [comment]
@naiyyar You probably want to do this:

```ruby
self.table_screen.open CommentScreen.new(blog: blog, nav: true)
```

Does that work?

**Comment by naiyyar** [comment]
Thank you @jamonholmgren for the help!

```
properties: {
                       screen: self
	              },
in custome cell
def screen=(val)
  @screen = val
end

@screen.open CommentScreen
```

This works for me.


your one line code should work as well i'll give it a try.

Thanks

**Comment by jamonholmgren** [comment]
Be careful of circular references in the code you're using there. Might want to use a WeakRef:

```ruby
def screen=(val)
  @screen = WeakRef.new(val)
end
```

**Comment by naiyyar** [comment]
Ok Thanks
I would prefer your way. looks easy

BTW, What is circular references and WeakRef ?

**Comment by jamonholmgren** [comment]
@naiyyar In RubyMotion, they use [automatic reference counting](https://en.wikipedia.org/wiki/Automatic_Reference_Counting) for garbage collection. They keep track of which object instances have references to them (like `var = MyObject.new`) and keep them alive as long as that reference is alive. When there are no more references, they garbage collect it.

The problem is if you have a circular reference, like so:

```
class Foo
  def set(a)
    @foo_ref = a
  end
end

a = Foo.new
b = Foo.new
c = Foo.new
a.set(b)
b.set(c)
c.set(a)

a = nil
b = nil
c = nil
```

In this case, the instances `a`, `b`, and `c` all have references to each other. So even when you unset all three variables, those `@foo_ref` vars will keep the others alive forever. This results in a memory leak.

However, if you changed the internal reference to a WeakRef:

```ruby
  def set(a)
    @foo_ref = WeakRef.new(a)
  end
```

Then it won't count those internal references, and at the end when `a` `b` and `c` are set to `nil`, the original object instances will get garbage collected, meaning no memory leaks.

Hope this helps!
